# Generated by Django 5.1.2 on 2026-04-26 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('pass_fail', 'Pass / Fail'), ('scale', 'Scale 1–5'), ('measurement', 'Measurement'), ('text', 'Text Note'), ('media', 'Media Required')], default='pass_fail', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('fail_triggers_flag', models.BooleanField(default=False, help_text='Auto-flag report if this item fails')),
                ('unit', models.CharField(blank=True, help_text='Unit for measurement items e.g. mm, kg', max_length=30)),
                ('help_text', models.TextField(blank=True, help_text='Guidance shown to inspector')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.checklisttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InspectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('level', models.CharField(choices=[('domain', 'Domain'), ('category', 'Category'), ('subcategory', 'Subcategory'), ('item_type', 'Item Type')], default='category', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('required_inspector_level', models.CharField(choices=[('junior', 'Junior'), ('senior', 'Senior'), ('specialist', 'Specialist')], default='junior', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inspections.inspectioncategory')),
            ],
            options={
                'verbose_name_plural': 'Inspection Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='inspections.inspectioncategory'),
        ),
        migrations.CreateModel(
            name='InspectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_id', models.CharField(blank=True, max_length=40, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField()),
                ('item_address', models.TextField(help_text='Full address / location of item')),
                ('item_age_years', models.PositiveIntegerField(blank=True, help_text='Age of item in years (affects complexity surcharge)', null=True)),
                ('is_complex', models.BooleanField(default=False, help_text='Mark if item is unusually complex')),
                ('scope', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('deep', 'Deep / Technical')], default='standard', max_length=20)),
                ('turnaround', models.CharField(choices=[('standard', 'Standard (24–48h)'), ('express', 'Express (Same Day)'), ('instant', 'Instant (Within Hours)')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('bill_sent', 'Bill Sent'), ('deposit_paid', 'Deposit Paid'), ('pre_inspection', 'Pre-Inspection'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('qa_review', 'QA Review'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked'), ('rescheduled', 'Rescheduled')], default='requested', max_length=20)),
                ('pre_inspection_notes', models.TextField(blank=True, help_text='Notes from pre-inspection readiness check')),
                ('reinspection_coverage', models.BooleanField(default=False, help_text='Client purchased re-inspection coverage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='inspections.inspectioncategory')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_template_version', models.PositiveIntegerField(default=1)),
                ('verdict', models.CharField(choices=[('pass', 'Pass'), ('conditional', 'Conditional'), ('fail', 'Fail')], max_length=20)),
                ('summary', models.TextField()),
                ('is_locked', models.BooleanField(default=False)),
                ('report_hash', models.CharField(blank=True, max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('qa_notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_inspection_reports', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_inspection_reports', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='inspections.inspectionrequest')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('deposit', 'Booking Deposit'), ('balance', 'Remaining Balance')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='inspection_payment_proofs/')),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_inspection_payments', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inspections.inspectionrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('bill_ready', 'Bill Ready'), ('payment_confirmed', 'Payment Confirmed'), ('payment_rejected', 'Payment Rejected'), ('assigned', 'Inspector Assigned'), ('in_progress', 'Inspection In Progress'), ('report_ready', 'Report Ready'), ('qa_returned', 'Report Returned for Revision'), ('reinspection_ready', 'Re-inspection Ready'), ('status_update', 'Status Update'), ('sla_breach', 'SLA Breach')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inspections.inspectionrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspection_evidence/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='inspections.checklistitem')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='inspections.inspectionrequest')),
            ],
            options={
                'ordering': ['captured_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_photo', models.ImageField(upload_to='inspection_checkins/')),
                ('checkin_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkin_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkin_at', models.DateTimeField(auto_now_add=True)),
                ('checkout_photo', models.ImageField(blank=True, null=True, upload_to='inspection_checkouts/')),
                ('checkout_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkout_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkout_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='inspections.inspectionrequest')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scope_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('turnaround_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('complexity_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('travel_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inspector_level_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reinspection_coverage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='inspections.inspectionrequest')),
            ],
        ),
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('speed_anomaly', 'Speed Anomaly'), ('no_checkin', 'Missing Check-In'), ('no_media', 'No Media Submitted'), ('gps_mismatch', 'GPS Mismatch'), ('pattern_match', 'Collusion Pattern')], max_length=30)),
                ('details', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fraud_flags', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to='inspections.inspectionrequest')),
            ],
        ),
        migrations.CreateModel(
            name='InspectorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('junior', 'Junior'), ('senior', 'Senior'), ('specialist', 'Specialist')], default='junior', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('performance_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('total_inspections', models.PositiveIntegerField(default=0)),
                ('total_flags', models.PositiveIntegerField(default=0)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certified_categories', models.ManyToManyField(blank=True, related_name='certified_inspectors', to='inspections.inspectioncategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manual_override', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='inspections.inspectionrequest')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inspections.inspectorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ReInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('discount_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_reinspection_of', to='inspections.inspectionrequest')),
                ('original_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinspections', to='inspections.inspectionrequest')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_reinspections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SLABreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=50)),
                ('breached_at', models.DateTimeField(auto_now_add=True)),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_sla_breaches', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_breaches', to='inspections.inspectionrequest')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='checklisttemplate',
            unique_together={('category', 'version')},
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_value', models.TextField()),
                ('flagged', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='inspections.checklistitem')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inspections.inspectionreport')),
            ],
            options={
                'unique_together': {('report', 'checklist_item')},
            },
        ),
    ]
