# Generated by Django 5.1.2 on 2026-04-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
