# Generated by Django 5.1.2 on 2026-04-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_fix_report_summary_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
