# Generated by Django 5.1.2 on 2026-04-27 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_inspectionreport_finalized_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionassignment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this the current active assignment?'),
        ),
        migrations.AlterField(
            model_name='inspectionassignment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inspections.inspectionrequest'),
        ),
    ]
