# Generated by Django 5.1.2 on 2026-04-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_inspectionassignment_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('bill_sent', 'Bill Sent'), ('awaiting_payment', 'Awaiting Payment'), ('deposit_paid', 'Deposit Paid'), ('pre_inspection', 'Pre-Inspection'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('qa_review', 'QA Review'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked'), ('rescheduled', 'Rescheduled')], default='requested', max_length=20),
        ),
    ]
