# Generated by Django 5.1.2 on 2026-04-28 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_alter_inspectionrequest_status'),
        ('marketplace', '0022_remove_userprofile_following_order_delivery_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionrequest',
            name='marketplace_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='inspectionrequest',
            name='product_snapshot',
            field=models.JSONField(blank=True, help_text='State of the product at the time of inspection request', null=True),
        ),
    ]
