# Generated by Django 5.1.2 on 2026-04-29 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_alter_inspectioncheckin_checkin_lat_and_more'),
        ('marketplace', '0024_faq_alter_lipanumber_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectioncategory',
            name='marketplace_category',
            field=models.ForeignKey(blank=True, help_text='Linked marketplace category for auto-suggestion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_categories', to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='inspectioncategory',
            name='product_origin',
            field=models.CharField(choices=[('any', 'Any'), ('local', 'Local/Native'), ('imported', 'Imported/External')], default='any', help_text='Whether this category applies to locally-made or imported products', max_length=20),
        ),
    ]
