# Generated by Django 5.1.2 on 2026-06-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_inspectioncategory_marketplace_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='section',
            field=models.CharField(default='General', help_text='Section group for checklist item e.g. Engine, Exterior', max_length=100),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='severity',
            field=models.CharField(choices=[('advisory', 'Advisory'), ('major', 'Major'), ('critical', 'Critical')], default='major', help_text='Severity level used for weighted quality scoring', max_length=20),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='grade',
            field=models.CharField(default='F', max_length=5),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
