# Generated by Django 5.1.2 on 2026-09-07 13:47

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_seed_checklists'),
        ('marketplace', '0089_alter_passwordresetrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionevidence',
            name='image',
            field=models.FileField(upload_to='inspection_evidence/'),
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='product_snapshot',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='State of the product at the time of inspection request', null=True),
        ),
        migrations.CreateModel(
            name='ProductInspectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('restock', 'Stock Restocked'), ('price_change', 'Price Changed'), ('condition_change', 'Condition Changed'), ('detail_change', 'Listing Details Changed'), ('image_change', 'Photos Changed'), ('variant_change', 'Variant Changed')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(blank=True, help_text='The inspection request whose baseline was active when this event occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_inspection_events', to='inspections.inspectionrequest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_events', to='marketplace.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
