# Generated by Django 5.1.2 on 2026-09-16 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_alter_inspectionevidence_image_and_more'),
        ('marketplace', '0097_alter_order_options_alter_payment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inspectionrequest',
            index=models.Index(fields=['status', '-created_at'], name='inspections_status_180836_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrequest',
            index=models.Index(fields=['client', '-created_at'], name='inspections_client__b065e1_idx'),
        ),
    ]
