# Generated by Django 5.1.2 on 2026-06-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('COMMISSION', 'Platform Commission'), ('CANCELLATION_FEE', 'Cancellation Fee'), ('REVERSAL', 'Commission Reversal')], default='COMMISSION', max_length=30),
        ),
    ]
