# Generated by Django 5.1.2 on 2026-09-05 06:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_commissionledgerentry_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyinvoice',
            name='subscription_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly subscription fee for this billing cycle', max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='total_amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total due = total_commission + subscription_fee', max_digits=12),
        ),
    ]
