# Generated by Django 5.1.2 on 2025-03-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_alter_follow_options_alter_like_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebaroffer',
            name='button_text',
            field=models.CharField(default='Learn More', help_text='Custom text for the offer button', max_length=50),
        ),
    ]
