# Generated by Django 5.1.2 on 2026-01-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_sidebaroffer_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
