# Generated by Django 5.1.2 on 2026-01-31 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_sidebaroffer_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='mobile-payments/')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('benefits', models.TextField(help_text='Comma-separated list or HTML for display')),
            ],
        ),
        migrations.CreateModel(
            name='LipaNamba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='marketplace.mobilenetwork')),
            ],
        ),
    ]
