# Generated by Django 5.1.2 on 2026-06-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_pickupcode_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='third_party_driver_info',
            field=models.CharField(blank=True, help_text='Info for third-party drivers (Name, Phone, etc.)', max_length=255),
        ),
    ]
