# Generated by Django 5.1.2 on 2026-06-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_warehouse_historicalroutepricing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalRoutePricing',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
