# Generated by Django 5.1.2 on 2026-07-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpayment',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
