# Generated by Django 5.1.2 on 2026-07-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_driverpayment_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(choices=[('line_haul', 'Line Haul (Warehouse-to-Warehouse)'), ('local_delivery', 'Local Delivery (Warehouse-to-Customer)')], default='line_haul', max_length=20),
        ),
    ]
