# Generated by Django 5.1.2 on 2026-07-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_shipment_shipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
