# Generated by Django 5.1.2 on 2026-07-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_shipment_shipped_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationping',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.AddIndex(
            model_name='locationping',
            index=models.Index(fields=['shipment', '-recorded_at'], name='logistics_l_shipmen_94cb98_idx'),
        ),
    ]
