# Generated by Django 5.1.2 on 2026-07-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_alter_locationping_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('arrived_at_warehouse', 'Arrived At Warehouse'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
