# Generated by Django 5.1.2 on 2026-01-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_userprofile_tier_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebaroffer',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('subscribed', 'Subscribed')], default='public', max_length=20),
        ),
    ]
