# Generated by Django 5.1.2 on 2026-04-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_sponsoredlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_banners/'),
        ),
    ]
