# Generated by Django 5.1.2 on 2026-04-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_userprofile_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('PICKUP', 'Physical Pickup'), ('DELIVERY', 'Home Delivery')], default='DELIVERY', max_length=15),
        ),
    ]
