# Generated by Django 5.1.2 on 2026-04-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_remove_userprofile_following_order_delivery_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoredlisting',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost of the promotion', max_digits=10),
        ),
        migrations.AddField(
            model_name='sponsoredlisting',
            name='duration_days',
            field=models.PositiveIntegerField(default=7, help_text='Duration of the promotion in days'),
        ),
    ]
