# Generated by Django 5.1.2 on 2026-06-17 10:32

import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_sitesettings_userprofile_preferred_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_code',
            field=models.CharField(blank=True, default=marketplace.models.generate_delivery_code, max_length=6, null=True),
        ),
    ]
