# Generated by Django 5.1.2 on 2026-06-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_product_latitude_product_location_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoredlisting',
            name='description',
            field=models.TextField(blank=True, help_text='Why should buyers check this out?', null=True),
        ),
        migrations.AlterField(
            model_name='sponsoredlisting',
            name='title',
            field=models.CharField(blank=True, help_text='Short, catchy title for the ad', max_length=200, null=True),
        ),
    ]
