# Generated by Django 5.1.2 on 2026-06-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_alter_sponsoredlisting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoredlisting',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text='Screenshot proof of payment', null=True, upload_to='promotion_proofs/'),
        ),
        migrations.AddField(
            model_name='sponsoredlisting',
            name='transaction_reference',
            field=models.CharField(blank=True, help_text='Transaction reference code', max_length=100, null=True),
        ),
    ]
