# Generated by Django 5.1.2 on 2026-06-22 12:17

import marketplace.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0030_sponsoredlisting_payment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Default platform commission % charged to sellers', max_digits=5),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Platform commission % charged to sellers on this tier', max_digits=5),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='tier_level',
            field=models.CharField(choices=[('customer', 'Customer'), ('seller_pro', 'Seller Pro'), ('business', 'Business')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/', validators=[marketplace.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='SokoniMax', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('customer', 'Customer'), ('seller_pro', 'Seller Pro'), ('business', 'Business')], default='customer', max_length=20),
        ),
    ]
