# Generated by Django 5.1.2 on 2026-06-23 02:25

from django.db import migrations

def update_company_name(apps, schema_editor):
    SiteSettings = apps.get_model('marketplace', 'SiteSettings')
    SiteSettings.objects.filter(company_name='UZASPEA').update(company_name='SokoniMax')

class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0035_product_size_product_weight_kg'),
    ]

    operations = [
        migrations.RunPython(update_company_name),
    ]
