# Generated by Django 5.1.2 on 2026-06-23 06:06

import django.db.models.deletion
import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0036_auto_20260623_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store_pictures/', validators=[marketplace.models.validate_image])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_images', to='marketplace.userprofile')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
