# Generated by Django 5.1.2 on 2026-06-23 09:29

import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0037_storeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerapplication',
            name='business_document',
            field=models.FileField(blank=True, null=True, upload_to='seller_applications/business/', validators=[marketplace.models.validate_document]),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='id_document',
            field=models.FileField(upload_to='seller_applications/id/', validators=[marketplace.models.validate_document]),
        ),
    ]
