# Generated by Django 5.1.2 on 2026-06-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0038_alter_sellerapplication_business_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='staff_reply',
            field=models.TextField(blank=True, help_text='Response visible to the ticket creator'),
        ),
    ]
