# Generated by Django 5.1.2 on 2026-06-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0039_supportticket_staff_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_location_verified',
            field=models.BooleanField(default=False),
        ),
    ]
