# Generated by Django 5.1.2 on 2026-06-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0041_order_platform_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='business_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='business_registration_number',
            field=models.CharField(blank=True, help_text='BRELA registration number or business license number', max_length=50),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='tin_number',
            field=models.CharField(blank=True, help_text='Tanzania Revenue Authority TIN number', max_length=30),
        ),
    ]
