# Generated by Django 5.1.2 on 2026-06-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0042_sellerapplication_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipanumber',
            name='purpose',
            field=models.CharField(choices=[('general', 'General'), ('subscriptions', 'Subscriptions & Upgrades'), ('commissions', 'Commission Payments')], default='general', max_length=20),
        ),
    ]
