# Generated by Django 5.1.2 on 2026-06-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0043_lipanumber_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipanumber',
            name='is_system',
            field=models.BooleanField(default=False, help_text='True if this is a global platform payment method'),
        ),
    ]
