# Generated by Django 5.1.2 on 2026-06-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0044_lipanumber_is_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CART', 'Cart'), ('CHECKOUT', 'Checkout'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PENDING_VERIFICATION', 'Pending Verification'), ('PAID', 'Paid'), ('SELLER_CONFIRMED', 'Seller Confirmed'), ('PREPARING', 'Preparing'), ('PACKAGING', 'Packaging'), ('SHIPPED_TO_WAREHOUSE', 'Shipped To Warehouse'), ('RECEIVED_AT_WAREHOUSE', 'Received At Warehouse'), ('ASSIGNED_TRANSPORT', 'Assigned Transport'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED_AT_REGIONAL_WAREHOUSE', 'Arrived At Regional Warehouse'), ('READY_FOR_PICKUP', 'Ready For Pickup'), ('READY_FOR_VEHICLE_HANDOVER', 'Ready For Vehicle Handover'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('DISPUTED', 'Disputed')], default='CART', max_length=40),
        ),
    ]
