# Generated by Django 5.1.2 on 2026-06-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0046_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
