# Generated by Django 5.1.2 on 2026-07-01 19:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0048_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='driver_payout_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text="Percentage of an order's shipping fee paid out to the delivering driver for standard (non-vehicle) deliveries.", max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CART', 'Cart'), ('CHECKOUT', 'Checkout'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PENDING_VERIFICATION', 'Pending Verification'), ('PAID', 'Paid'), ('PAID_PRODUCT', 'Paid Product'), ('SELLER_CONFIRMED', 'Seller Confirmed'), ('PREPARING', 'Preparing'), ('PACKAGING', 'Packaging'), ('SHIPPED_TO_WAREHOUSE', 'Shipped To Warehouse'), ('RECEIVED_AT_WAREHOUSE', 'Received At Warehouse'), ('AWAITING_DELIVERY_PAYMENT', 'Awaiting Delivery Payment'), ('PENDING_DELIVERY_VERIFICATION', 'Pending Delivery Verification'), ('ASSIGNED_TRANSPORT', 'Assigned Transport'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED_AT_REGIONAL_WAREHOUSE', 'Arrived At Regional Warehouse'), ('READY_FOR_PICKUP', 'Ready For Pickup'), ('READY_FOR_VEHICLE_HANDOVER', 'Ready For Vehicle Handover'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED_DELIVERY', 'Failed Delivery'), ('EXPIRED', 'Expired'), ('DISPUTED', 'Disputed')], default='CART', max_length=40),
        ),
    ]
