# Generated by Django 5.1.2 on 2026-07-02 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0050_category_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='max_team_members',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of team members allowed on this tier. Leave blank for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='invitation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False to suspend access without losing the permission configuration.'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_preset',
            field=models.CharField(blank=True, help_text='Optional label of the role preset this member was invited under, for display purposes only. The `permissions` field is always the actual source of truth.', max_length=30),
        ),
        migrations.CreateModel(
            name='TeamMemberAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('permissions_changed', 'Permissions Changed'), ('suspended', 'Suspended'), ('reactivated', 'Reactivated'), ('removed', 'Removed')], max_length=30)),
                ('detail', models.JSONField(blank=True, default=dict, help_text="e.g. {'before': {...}, 'after': {...}} for permission changes")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_audit_entries_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_audit_entries_about_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
