# Generated by Django 5.1.2 on 2026-07-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0055_order_discount_amount_promocode_order_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: Square image (1:1 aspect ratio) with centered subject (e.g., 400x400px). Rectangular images will be cropped to center in circular displays.', null=True, upload_to='category_images/'),
        ),
    ]
