# Generated by Django 5.1.2 on 2026-07-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0056_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('customer', 'Customer'), ('worker', 'Worker'), ('seller_pro', 'Seller Pro'), ('business', 'Business')], default='customer', max_length=20),
        ),
    ]
