# Generated by Django 5.1.2 on 2026-07-23 08:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0057_alter_userprofile_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_order_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('piece', 'Piece(s)'), ('kg', 'Kilogram(s)'), ('ton', 'Ton(s)'), ('liter', 'Liter(s)'), ('box', 'Box(es)'), ('dozen', 'Dozen(s)'), ('pair', 'Pair(s)'), ('meter', 'Meter(s)')], default='piece', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='ProductPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='marketplace.product')),
            ],
            options={
                'ordering': ['min_quantity'],
            },
        ),
    ]
