# Generated by Django 5.1.2 on 2026-07-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0058_product_minimum_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_type',
            field=models.CharField(choices=[('PLATFORM_DELIVERY', 'Platform Delivery'), ('DIRECT_DELIVERY', 'Direct Delivery'), ('WAREHOUSE_PICKUP', 'Warehouse Pickup'), ('SELLER_PICKUP', 'Seller Pickup')], default='PLATFORM_DELIVERY', max_length=30),
        ),
    ]
