# Generated by Django 5.1.2 on 2026-07-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0060_message_marketplace_convers_64eb0c_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
    ]
