# Generated by Django 5.1.2 on 2026-07-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0065_alter_order_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
