# Generated by Django 5.1.2 on 2026-07-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0066_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Part code, SKU, or serial number', max_length=100, null=True),
        ),
    ]
