# Generated by Django 5.1.2 on 2026-07-29 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0067_product_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='requires_quote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CART', 'Cart'), ('CHECKOUT', 'Checkout'), ('REQUESTED_INVOICE', 'Requested Invoice'), ('INVOICE_GENERATED', 'Invoice Generated'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PENDING_VERIFICATION', 'Pending Verification'), ('PAID', 'Paid'), ('PAID_PRODUCT', 'Paid Product'), ('SELLER_CONFIRMED', 'Seller Confirmed'), ('PREPARING', 'Preparing'), ('PACKAGING', 'Packaging'), ('SHIPPED_TO_WAREHOUSE', 'Shipped To Warehouse'), ('RECEIVED_AT_WAREHOUSE', 'Received At Warehouse'), ('AWAITING_DELIVERY_PAYMENT', 'Awaiting Delivery Payment'), ('PENDING_DELIVERY_VERIFICATION', 'Pending Delivery Verification'), ('ASSIGNED_TRANSPORT', 'Assigned Transport'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED_AT_REGIONAL_WAREHOUSE', 'Arrived At Regional Warehouse'), ('READY_FOR_PICKUP', 'Ready For Pickup'), ('READY_FOR_VEHICLE_HANDOVER', 'Ready For Vehicle Handover'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED_DELIVERY', 'Failed Delivery'), ('EXPIRED', 'Expired'), ('DISPUTED', 'Disputed'), ('RETURNED_TO_WAREHOUSE', 'Returned To Warehouse')], default='CART', max_length=40),
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('request_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_requested', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_product_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_product_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_count', '-last_requested'],
                'unique_together': {('name', 'seller')},
            },
        ),
    ]
