# Generated by Django 5.1.2 on 2026-07-29 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0068_product_requires_quote_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_requests', to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='New', max_length=4),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product-requests/'),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='requires_quote',
            field=models.BooleanField(default=False),
        ),
    ]
