# Generated by Django 5.1.2 on 2026-08-02 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0070_product_buying_price_productrequest_buying_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', '-created_at'], name='marketplace_seller__d3a46e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available', 'stock'], name='marketplace_is_avai_46b15c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['condition'], name='marketplace_conditi_8510af_idx'),
        ),
    ]
