# Generated by Django 5.1.2 on 2026-08-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0072_supportticket_priority_ticketmessage'),
    ]

def migrate_messages(apps, schema_editor):
    SupportTicket = apps.get_model('marketplace', 'SupportTicket')
    TicketMessage = apps.get_model('marketplace', 'TicketMessage')
    
    for ticket in SupportTicket.objects.all():
        if ticket.message:
            TicketMessage.objects.create(
                ticket=ticket,
                sender=ticket.user,
                sender_name=ticket.name,
                body=ticket.message,
                is_internal=False,
                created_at=ticket.created_at
            )
        if ticket.staff_reply:
            TicketMessage.objects.create(
                ticket=ticket,
                sender=ticket.assigned_to,
                sender_name="Staff" if not ticket.assigned_to else ticket.assigned_to.first_name,
                body=ticket.staff_reply,
                is_internal=False,
                created_at=ticket.updated_at
            )
        if ticket.staff_notes:
            TicketMessage.objects.create(
                ticket=ticket,
                sender=ticket.assigned_to,
                sender_name="Staff" if not ticket.assigned_to else ticket.assigned_to.first_name,
                body=ticket.staff_notes,
                is_internal=True,
                created_at=ticket.updated_at
            )

def reverse_migrate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0072_supportticket_priority_ticketmessage'),
    ]

    operations = [
        migrations.RunPython(migrate_messages, reverse_migrate)
    ]
