# Generated by Django 5.1.2 on 2026-08-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0073_migrate_ticket_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='message',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='staff_notes',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='staff_reply',
        ),
    ]
