# Generated by Django 5.1.2 on 2026-08-20 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0074_remove_supportticket_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='negotiation_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Full Facebook profile or page URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Full LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tiktok_username',
            field=models.CharField(blank=True, help_text='TikTok username without @', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_username',
            field=models.CharField(blank=True, help_text='Twitter/X username without @', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code, e.g. +255712345678', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', message="WhatsApp number format: '+255712345678'. Up to 15 digits allowed.")]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Full YouTube channel URL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CART', 'Cart'), ('CHECKOUT', 'Checkout'), ('REQUESTED_INVOICE', 'Requested Invoice'), ('INVOICE_GENERATED', 'Invoice Generated'), ('BUYER_COUNTERED', 'Buyer Countered'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PENDING_VERIFICATION', 'Pending Verification'), ('PAID', 'Paid'), ('PAID_PRODUCT', 'Paid Product'), ('SELLER_CONFIRMED', 'Seller Confirmed'), ('PREPARING', 'Preparing'), ('PACKAGING', 'Packaging'), ('SHIPPED_TO_WAREHOUSE', 'Shipped To Warehouse'), ('RECEIVED_AT_WAREHOUSE', 'Received At Warehouse'), ('AWAITING_DELIVERY_PAYMENT', 'Awaiting Delivery Payment'), ('PENDING_DELIVERY_VERIFICATION', 'Pending Delivery Verification'), ('ASSIGNED_TRANSPORT', 'Assigned Transport'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED_AT_REGIONAL_WAREHOUSE', 'Arrived At Regional Warehouse'), ('READY_FOR_PICKUP', 'Ready For Pickup'), ('READY_FOR_VEHICLE_HANDOVER', 'Ready For Vehicle Handover'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED_DELIVERY', 'Failed Delivery'), ('EXPIRED', 'Expired'), ('DISPUTED', 'Disputed'), ('RETURNED_TO_WAREHOUSE', 'Returned To Warehouse')], default='CART', max_length=40),
        ),
    ]
