# Generated by Django 5.1.2 on 2026-08-21 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0075_order_negotiation_data_userprofile_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Category-specific attributes (e.g. oem_part_number, placement, brand)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=20),
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='marketplace.vehiclemake')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('make', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('trim', models.CharField(blank=True, max_length=100, null=True)),
                ('engine', models.CharField(blank=True, help_text='e.g. 2.5L 4-Cyl, 3.0L V6 Turbo', max_length=150, null=True)),
                ('drivetrain', models.CharField(blank=True, help_text='e.g. FWD, AWD, RWD', max_length=50, null=True)),
                ('transmission', models.CharField(blank=True, help_text='e.g. 6-Speed Automatic', max_length=100, null=True)),
                ('body_style', models.CharField(blank=True, help_text='e.g. Sedan, SUV, Crew Cab', max_length=100, null=True)),
                ('region', models.CharField(default='US', help_text='Market spec (US, EU, JDM, GCC)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='marketplace.vehiclemake')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='marketplace.vehiclemodel')),
            ],
            options={
                'ordering': ['make', 'model', '-year', 'trim'],
            },
        ),
        migrations.CreateModel(
            name='ProductVehicleFitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitment_notes', models.CharField(blank=True, help_text='e.g., Fits AWD models only', max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=True, help_text='Verified fitment vs user-submitted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='marketplace.product')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='marketplace.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['product'], name='marketplace_product_76750b_idx'), models.Index(fields=['vehicle'], name='marketplace_vehicle_b10aad_idx')],
                'unique_together': {('product', 'vehicle')},
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['make', 'model', 'year'], name='marketplace_make_id_79c46e_idx'),
        ),
    ]
