# Generated by Django 5.1.2 on 2026-08-22 08:48

import django.db.models.deletion
import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0076_vehiclemake_product_specifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', validators=[marketplace.models.validate_image])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='is_leaf',
            field=models.BooleanField(default=False, help_text='True if this is an end-node category'),
        ),
        migrations.AddField(
            model_name='category',
            name='spec_schema',
            field=models.JSONField(blank=True, default=list, help_text='List of dicts defining specs for this category'),
        ),
        migrations.AddField(
            model_name='product',
            name='structured_specs',
            field=models.JSONField(blank=True, default=dict, help_text="Specs matching the category's spec_schema"),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketplace.brand'),
        ),
        migrations.CreateModel(
            name='ReferenceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reference_products/', validators=[marketplace.models.validate_image])),
                ('structured_specs', models.JSONField(blank=True, default=dict, help_text='Definitive specs for this model')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_products', to='marketplace.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_products', to='marketplace.category')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='reference_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='marketplace.referenceproduct'),
        ),
    ]
