# Generated by Django 5.1.2 on 2026-08-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0077_brand_category_is_leaf_category_spec_schema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Refurbished', 'Refurbished'), ('Like_New', 'Like New')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Refurbished', 'Refurbished'), ('Like_New', 'Like New')], default='New', max_length=20),
        ),
    ]
