# Generated by Django 5.1.2 on 2026-08-24 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0078_alter_product_condition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False, help_text='True if listing is saved as draft and not published'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_draft', 'seller', '-created_at'], name='marketplace_is_draf_47ce1d_idx'),
        ),
    ]
