# Generated by Django 5.1.2 on 2026-08-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0079_product_is_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(blank=True, default='piece', max_length=50),
        ),
    ]
