# Generated by Django 5.1.2 on 2026-08-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0080_alter_product_unit_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brands',
            field=models.ManyToManyField(blank=True, help_text='Brands applicable to this category', related_name='categories', to='marketplace.brand'),
        ),
    ]
