# Generated by Django 5.1.2 on 2026-08-25 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0082_brand_created_at_brand_created_by_brand_is_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='referenceproduct',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reference_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referenceproduct',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=True, help_text='True if verified/canonical, False if dynamically added by user'),
        ),
        migrations.AddField(
            model_name='referenceproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
