# Generated by Django 5.1.2 on 2026-08-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0084_productrequest_fulfilled_product_productrequestvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_product_requests',
            field=models.BooleanField(default=True, help_text='Show Coming Soon / Requested items tab on profile'),
        ),
    ]
