# Generated by Django 5.1.2 on 2026-08-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0085_userprofile_show_product_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_bulk_order',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
