# Generated by Django 5.1.2 on 2026-08-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0086_order_is_bulk_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Optional direct phone number for team member.', max_length=30),
        ),
        migrations.AddField(
            model_name='teammember',
            name='created_by_owner',
            field=models.BooleanField(default=False, help_text='True if the user account was directly provisioned by the business owner.'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes by the business owner regarding this team member.'),
        ),
        migrations.AlterField(
            model_name='teammemberauditlog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Account Created'), ('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('permissions_changed', 'Permissions Changed'), ('password_reset', 'Password Reset'), ('suspended', 'Suspended'), ('reactivated', 'Reactivated'), ('transferred', 'Role Transferred'), ('removed', 'Removed')], max_length=30),
        ),
    ]
