# Generated by Django 5.1.2 on 2026-09-06 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0087_teammember_contact_phone_teammember_created_by_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('settings_change', 'Settings Password Change'), ('forgot_password', 'Forgot Password')], default='forgot_password', max_length=20)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('pending_password_hash', models.CharField(blank=True, help_text='Hashed new password for settings change requests', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Dispatch'), ('dispatched', 'Dispatched by Admin'), ('completed', 'Completed'), ('expired', 'Expired'), ('superseded', 'Superseded')], db_index=True, default='pending', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_password_resets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='marketplace_token_ca48ff_idx'), models.Index(fields=['status', 'is_used', 'expires_at'], name='marketplace_status_82b1af_idx'), models.Index(fields=['user', 'status'], name='marketplace_user_id_f102e1_idx')],
            },
        ),
    ]
