# Generated by Django 5.1.2 on 2026-09-06 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0088_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Password Change Request', 'verbose_name_plural': 'Password Change Requests'},
        ),
    ]
