# Generated by Django 5.1.2 on 2026-09-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0089_alter_passwordresetrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('unspecified', 'Unspecified')], default='unspecified', max_length=15),
        ),
    ]
