# Generated by Django 5.1.2 on 2026-09-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0090_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='for_you_image',
            field=models.ImageField(blank=True, help_text="Custom image shown inside the rotating 'For You' circle in the category bar.", null=True, upload_to='site_settings/'),
        ),
    ]
