# Generated by Django 5.1.2 on 2026-09-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0091_sitesettings_for_you_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='a_plus_content',
            field=models.JSONField(blank=True, default=dict, help_text='A+ Content modules (banners, spotlights, infographics)'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_a_plus_content',
            field=models.BooleanField(db_index=True, default=False, help_text='Enable Amazon-style A+ Content'),
        ),
    ]
