# Generated by Django 5.1.2 on 2026-09-11 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0092_product_a_plus_content_product_has_a_plus_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedUsername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, help_text='Canonical lowercase username to reserve', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('system', 'System & Routing'), ('staff_official', 'Staff & Platform Security'), ('brand_trademark', 'Brand & Trademark'), ('vip_premium', 'VIP & Premium Word'), ('banned', 'Inappropriate or Banned')], db_index=True, default='brand_trademark', max_length=30)),
                ('reason', models.TextField(blank=True, help_text="Explanation e.g. 'Registered trademark of Toyota Motor Corporation' or 'Core system path'")),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='When active, this username cannot be registered by regular users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reserved_for', models.ForeignKey(blank=True, help_text='Optional: Assign this handle to a verified official seller or platform account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reserved_usernames', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserved Username',
                'verbose_name_plural': 'Reserved Usernames',
                'ordering': ['username'],
            },
        ),
    ]
