# Generated by Django 5.1.2 on 2026-09-11 21:30

import django.db.models.deletion
import django.utils.timezone
import marketplace.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0093_reservedusername'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerSiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(help_text='Physical store street address, building, or landmark')),
                ('region', models.CharField(blank=True, default='Dar es Salaam', max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('storefront_image', models.ImageField(blank=True, null=True, upload_to='site_visits/storefront/', validators=[marketplace.models.validate_image])),
                ('interior_image', models.ImageField(blank=True, null=True, upload_to='site_visits/interior/', validators=[marketplace.models.validate_image])),
                ('document_image', models.FileField(blank=True, null=True, upload_to='site_visits/documents/', validators=[marketplace.models.validate_document])),
                ('staff_notes', models.TextField(blank=True, help_text='Notes and observations from inspecting staff')),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_site_visits', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to=settings.AUTH_USER_MODEL)),
                ('visited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_site_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
