# Generated by Django 5.1.2 on 2026-09-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0095_sitesettings_linkedin_url_sitesettings_tiktok_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-is_pinned', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='faq',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin this FAQ to appear at the top'),
        ),
    ]
