# Generated by Django 5.1.2 on 2026-04-27 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staffprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancelling the task'),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_notes',
            field=models.TextField(blank=True, help_text='Notes provided upon task completion'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_categories', to='staff.department'),
        ),
        migrations.AlterField(
            model_name='staffpermission',
            name='permission',
            field=models.CharField(choices=[('can_confirm_upgrades', 'Confirm User Upgrades'), ('can_verify_requests', 'Verify Requests'), ('can_approve_content', 'Approve Content'), ('can_review_promotions', 'Review Promotions'), ('can_moderate', 'Moderate Content'), ('can_manage_users', 'Manage Users'), ('can_view_reports', 'View Reports'), ('can_manage_tasks', 'Manage Tasks'), ('can_approve_actions', 'Approve Staff Actions'), ('can_manage_inspections', 'Manage All Inspections')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
