# Generated by Django 5.1.2 on 2026-06-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_task_cancellation_reason_task_completion_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpermission',
            name='permission',
            field=models.CharField(choices=[('can_confirm_upgrades', 'Confirm User Upgrades'), ('can_verify_requests', 'Verify Requests'), ('can_approve_content', 'Approve Content'), ('can_review_promotions', 'Review Promotions'), ('can_moderate', 'Moderate Content'), ('can_manage_users', 'Manage Users'), ('can_view_reports', 'View Reports'), ('can_manage_tasks', 'Manage Tasks'), ('can_approve_actions', 'Approve Staff Actions'), ('can_manage_inspections', 'Manage All Inspections'), ('can_manage_warehouse_intake', 'Manage Warehouse Intake'), ('can_manage_warehouse_transfers', 'Manage Warehouse Transfers'), ('can_manage_logistics', 'Manage Logistics')], max_length=50),
        ),
    ]
