# Generated by Django 5.1.2 on 2026-06-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_remove_warehouse_location_name_warehouse_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseintake',
            name='seller_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded seller signature', null=True),
        ),
        migrations.AddField(
            model_name='warehouseintake',
            name='staff_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded staff signature', null=True),
        ),
    ]
