# Generated by Django 5.1.2 on 2026-06-29 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_warehouseintake_seller_signature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRoutePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_points', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_prices', to='warehouses.warehouse')),
                ('origin_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_prices', to='warehouses.warehouse')),
            ],
            options={
                'unique_together': {('origin_warehouse', 'destination_warehouse')},
            },
        ),
    ]
