# Generated by Django 5.1.2 on 2026-07-01 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_historicalroutepricing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=False, help_text='Managers can edit/void intake records and view reports for this warehouse.')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_assignments', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Staff Assignment',
                'verbose_name_plural': 'Warehouse Staff Assignments',
                'unique_together': {('user', 'warehouse')},
            },
        ),
    ]
