# Generated by Django 5.1.2 on 2026-07-26 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('warehouses', '0005_add_warehouse_staff_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='region',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.region'),
        ),
    ]
