# Generated by Django 5.1.2 on 2026-09-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_district_latitude_district_longitude_region_latitude_and_more'),
        ('warehouses', '0006_alter_warehouse_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active'], name='warehouses__is_acti_0f15f9_idx'),
        ),
    ]
